/*
 * This source file was generated by the Gradle 'init' task
 */
package bcc.textDecisionGame;

public class App {
    public static void main(String[] args) {








        Scanner scanner = new Scanner(System.in);
        System.out.println("Welcome to the College Decision Game!");

        // Decision 1
        System.out.println("Scenario 1: You are finishing high school. Do you want to (1) apply to college or (2) take a gap year?");
        int choice1 = getChoice(scanner, 2);

        if (choice1 == 1) {
            // Decision 2
            System.out.println("Scenario 2: You get accepted to a good college. Do you (1) accept the offer or (2) look for scholarships?");
            int choice2 = getChoice(scanner, 2);

            if (choice2 == 1) {
                // Decision 3
                System.out.println("Scenario 3: College is expensive. Do you (1) get a part-time job or (2) focus only on studies?");
                int choice3 = getChoice(scanner, 2);
                if (choice3 == 1) {
                    System.out.println("Final result: You balance work and study, graduate with honors, and land a great job!");
                } else {
                    System.out.println("Final result: You excel academically, but struggle financially. You graduate, but with debt.");
                }
            } else {
                System.out.println("Final result: You win a scholarship and attend college for free! Life is good.");
            }
        } else {
            // Decision 2 for gap year
            System.out.println("Scenario 2: During your gap year, do you (1) travel or (2) work?");
            int choice2 = getChoice(scanner, 2);
            if (choice2 == 1) {
                // Decision 3
                System.out.println("Scenario 3: You discover a passion for photography. Do you (1) pursue it professionally or (2) go to college next year?");
                int choice3 = getChoice(scanner, 2);
                if (choice3 == 1) {
                    System.out.println("Final result: You become a successful photographer and travel the world!");
                } else {
                    System.out.println("Final result: You go to college with new experiences and do well.");
                }
            } else {
                System.out.println("Final result: You save money and feel ready for college next year.");
            }
        }
        scanner.close();
    }

    private static int getChoice(Scanner scanner, int options) {
        int choice = 0;
        while (true) {
            System.out.print("Enter your choice (1-" + options + "): ");
            String input = scanner.nextLine();
            try {
                choice = Integer.parseInt(input);
                if (choice >= 1 && choice <= options) {
                    break;
                }
            } catch (NumberFormatException e) {
                // ignore and reprompt
            }
            System.out.println("Invalid choice. Please try again.");
        }
        return choice;
    }
    }
}
